# Generated by Django 4.2 on 2023-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="name",
            field=models.CharField(
                choices=[("savings", "savings"), ("current", "current")],
                max_length=20,
                unique=True,
                verbose_name="Account type",
            ),
        ),
    ]
