# Generated by Django 4.2 on 2023-05-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactions",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="transactions",
            name="receiver_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="account.account",
                verbose_name="Receiver account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer", "transfer"),
                    ("withdraw", "withdraw"),
                    ("deposit", "deposit"),
                    ("INTEREST", "INTEREST"),
                ],
                max_length=50,
                verbose_name="Transaction type",
            ),
        ),
    ]
